apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "recipe-ai.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recipe-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "recipe-ai.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "recipe-ai.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: recipe-ai
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          env:
            - name: ANTHROPIC_API_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-ai.fullname" . }}-secret
                  key: anthropic-api-key
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-ai.fullname" . }}-secret
                  key: secret-key
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: {{ include "recipe-ai.fullname" . }}-secret
                  key: database-url
            {{- range $key, $value := .Values.deployment.env }}
            - name: {{ $key }}
              value: {{ $value | quote }}
            {{- end }}
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}