apiVersion: v1
kind: Service
metadata:
  name: {{ include "recipe-ai.fullname" . }}-postgres
  labels:
    {{- include "recipe-ai.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: postgres
    protocol: TCP
    name: postgres
  selector:
    {{- include "recipe-ai.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database