version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ../:/workspace:cached
    command: sleep infinity
    environment:
      - DATABASE_URL=postgresql://recipe_user:recipe_dev_password@postgres:5432/recipe_db?sslmode=disable
    ports:
      - "8000:8000"
      - "5432:5432"
    depends_on:
      - postgres
    networks:
      - devcontainer_network

  postgres:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: recipe_db
      POSTGRES_USER: recipe_user
      POSTGRES_PASSWORD: recipe_dev_password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - devcontainer_network

networks:
  devcontainer_network:
    driver: bridge

volumes:
  postgres-data: