namespace: recipe-ai

image:
  repository: registry.k8s.blacktoaster.com/ai-recipe/ai-recipe
  tag: latest
  pullPolicy: IfNotPresent

deployment:
  replicaCount: 1
  containerPort: 8000
  env:
    GIN_MODE: release
    CLAUDE_MODEL: "claude-sonnet-4-20250514"
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi

service:
  type: ClusterIP
  port: 80
  targetPort: 8000

ingress:
  enabled: true
  className: nginx
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
  hosts:
    - host: recipes.k8s.blacktoaster.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: recipe-ai-tls
      hosts:
        - recipes.k8s.blacktoaster.com

externalDNS:
  target: "pi5.k8s.blacktoaster.com"

certificate:
  enabled: true
  name: recipe-ai
  commonName: recipe-ai.k8s.blacktoaster.com
  issuerRef:
    name: vault-issuer
    kind: ClusterIssuer
    group: cert-manager.io
  dnsNames:
    - recipes.k8s.blacktoaster.com

secrets:
  # For helm install --set, these will be automatically base64 encoded
  anthropicApiKey: ""
  secretKey: ""

postgres:
  enabled: true
  database: "recipe_db"
  username: "recipe_user"
  password: "recipe_password_change_me"
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi
  
  persistence:
    enabled: true
    size: 2Gi
    accessMode: ReadWriteOnce
    # storageClass: ""  # Use default storage class

# Vault Secrets Operator configuration
vaultSecretsOperator:
  enabled: false
  mount: "secret"
  path: "recipe-ai/secrets"
  refreshAfter: "30s"
  vaultAuthRef: "default"
