apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipe-ai.fullname" . }}-postgres-secret
  labels:
    {{- include "recipe-ai.labels" . | nindent 4 }}
type: Opaque
data:
  password: {{ .Values.postgres.password | b64enc | quote }}