{{- if not .Values.vaultSecretsOperator.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "recipe-ai.fullname" . }}-secret
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "recipe-ai.labels" . | nindent 4 }}
type: Opaque
data:
  anthropic-api-key: {{ .Values.secrets.anthropicApiKey | b64enc }}
  secret-key: {{ .Values.secrets.secretKey | b64enc }}
{{- end }}